# server port
server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.1.80.120:3306/ECP_USER
    username: portal
    password: okestro1
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      naming:
        physical-strategy: okestro.servicebroker.configuration.jpa.CustomPhysicalNamingStrategy
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    openservicebroker:
      catalog:
        services:
          - id: de40e97e-0bb5-466c-84ef-7ec85ec7315d
            name: redis-paas
            description: redis
            plans:
              - id: afe580b0-e344-4917-9b7c-db2b3849b782
                name: standard
                description: standard
          - id: cc8bdec3-ce74-4971-86bc-4c72cc255c7a
            name: rabbitmq-paas
            description: rabbitmq
            plans:
              - id: 6aa752f8-2398-4d6f-89a3-8cfed0a1c0e6
                name: standard
                description: standard

# log
logging:
  level:
    sample: debug
#######
# api url
api:
  url:
    k8s: http://localhost:1001/
#######




k8s:
  url: https://10.1.80.100:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpqcktIaHFNdGJWTlFyM1JoU3V0VUp1Q05xRF81RDBwbXQ5ME56QVprZ28ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNhLWFkbWluLXRva2VuLWd3NWt6Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InNhLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMzY4MmIyMjMtZDRiOC00YzAxLThhYmItNzYyNGFjZjY1YWU0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6c2EtYWRtaW4ifQ.f3lWr8pmq0DHWBoMotwI_w1g4taj6bAuFLO0uB9uD0SgI1WIaXvuddHOZL4WPWNepOm_lo02GqF6yO3ZOJBigEa8v0PnDJGkLvJLVsZD6GEwhKfDQ3hPIG0cE3m_DiKt4Pl0QDrQ0E-eFd6jXLpgSkwhVjlapR8abm9_45NgqsGEDOFc00wAUVOUg0CI5554fpukbolu6WZ2GZqJPP316kP9S1OtCKG08h-Z7g3Xk1OXXLkHspH_eK4SsK0A8fnUwP_Jpazy4WCtfe8e7aUybBOblzRHsWWKstsbhtGLmGz3y8Ofmtcq4oc0VdNHUP4E6y-vqW1OdSobFfI31GKG5w
  username: root
  password: okestro1
